using CreateOrderApp.Core.Entities;
using System;
using System.Collections.Generic;
using System.Text;

namespace CreateOrderApp.Entities.Concrete
{
	/// <summary>
	/// Generated by ElementalBuilder -- Enes Karaçomak (21.03.2022 11:51:25)
	/// </summary>
	public class OrderLine:IEntity
	{
		#region Properties 
		public Int32 Id { get; set; }
		public Int32 OrderId { get; set; }
		public Int32 ProductId { get; set; }
		public decimal LineDiscount { get; set; }
		public decimal LineTax { get; set; }
		#endregion 

	}
}
	// C:\Users\enesk\source\repos\CreateOrderApp\CreateOrderApp.Entities\Concrete 
