	//*** Generated by ElementalBuilder (21.03.2022 11:51:25)  ***//
	//*** EnesKaracomak  ***//
using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.IdentityModel.Tokens;

namespace CreateOrderApp.Core.Utilities.Security.Encyption
{
	public class SigningCredentialsHelper 
	{
		public static SigningCredentials CreateSigningCredentials(SecurityKey securityKey)
		{
			return new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256Signature);
		}
	}
}
	// C:\Users\enesk\source\repos\CreateOrderApp\CreateOrderApp.Core\Utilities\Security\Encyption 
