	//*** Generated by ElementalBuilder (21.03.2022 11:51:25)  ***//
	//*** EnesKaracomak  ***//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Autofac.Extensions.DependencyInjection;
using CreateOrderApp.Business.DependencyResolvers.Autofac;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace CreateOrderApp.WebApi
{
	public class Program
	{
		public static void Main(string[] args) 
		{
		CreateHostBuilder(args).Build().Run(); 
		} 
		public static IHostBuilder CreateHostBuilder(string[] args) => Host.CreateDefaultBuilder(args)
			.UseServiceProviderFactory(new AutofacServiceProviderFactory())
			.ConfigureContainer<ContainerBuilder>(builder =>
			{
				builder.RegisterModule(new AutofacBusinessModule());
			})
			.ConfigureWebHostDefaults(webBuilder =>
			{
				webBuilder.UseStartup<Startup>();
			});
	}
}
	// C:\Users\enesk\source\repos\CreateOrderApp\CreateOrderApp.WebApi 
